//
//  Visual MacStandardBasic
//
//  Copyright 1999 Nick Vellios. All rights reserved.
//
//  This code is licensed under the "Take a kid fishing or hunting license"
//  See website or email below for details.
//
//  nick@vellios.com
//  http://www.Vellios.com
//
struct cmd_list    //These are built-in cmds, there will also be user defined subs
{
    short num;
    char name[16];
    char params[10];
} cmd_list[500] =
        {
                // F For
                // P Pointer(long rcv var)
                // L Long (argument)
                // l Possible Long (argument)
                // S String (argument)
                // g Select
                // h Case
                // i EndCase
                // k Default
                // R Sub
                // A Array
                // E Either Num or Str Argument
                // T 'THEN'
                // t 'TO'
                // s STEP(optional)
                // N 'NEXT'
                // W WHILE OR UNTIL decides code
                // J Jump Label
                // = Assignment
                // p Special Print statement
                // B Loop Operation
                // C IF
                // e else
                // f endif
                // c small c equals ctl ident a (ident or var )
                // w small w equal form window ident
                51, "DIM", "Z",
                101, "LET", "Q",
                102, "NONE", "Z",
                103, "END", "Z",
                104, "STOP", "Z",
                105, "GOTO", "J",
                106, "BEEP", "Z",
                107, "IF", "CLT",
                108, "ELSE", "e",
                109, "ENDIF", "f",
                110, "DO", "WL",
                111, "LOOP", "B",
                113, "GOSUB", "J",
                114, "RETURN", "Z",
                115, "EXITLOOP", "b",
                116, "EXITSUB", "Z",
                117, "EXITFUNCTION", "E",
                117, "EXITF", "E",
                118, "FOR", "FVj=LtLs",
                119, "NEXT", "VN",
                120, "PRINT", "a",
                121, "WINDOW", "VLLLLLSR",
                122, "WINCLOSE", "w",
                122, "WCLOSE", "w",
                123, "LINE", "wLLLL",
                124, "BOX", "wLLLL",
                125, "CIRCLE", "wLLL",
                126, "ELLIPSE", "wLLLL",
                127, "BUTTON", "VwLLLLSR",
                128, "CHECKBOX", "VwLLLLSR",
                128, "CBOX", "VwLLLLSR",
                129, "RADIO", "VwLLLLLSR",
                129, "RADIOBUTTON", "VwLLLLLSR",
                130, "SCROLLBAR", "VwLLLLR",
                130, "SCROLL", "VwLLLLR",
                131, "MOVETO", "wLL",
                132, "POINT", "wLL",
                133, "TEXTBOX", "VwLLLLLSR",
                134, "MENUADD", "LSR",
                135, "MENUAPPLE", "Z",
                136, "MENUADDITEM", "LSSR",
                137, "MENUDESK", "Z",
                138, "SELECT", "g",
                139, "CASE", "h",
                140, "ENDCASE", "i",
                141, "DEFAULT", "k",
                142, "WINMOVE", "wLL",
                143, "WINSIZE", "wLL",
                144, "WINTITLE", "wS",
                145, "SAY", "S",
                146, "CTLREMOVE", "c",
                147, "CTLHIDE", "c",
                148, "CTLSHOW", "c",
                149, "CTLDISABLE", "c",
                150, "CTLENABLE", "c",
                151, "CTLSIZE", "cLL",
                152, "CTLMOVE", "cLL",
                153, "WINHIDE", "w",
                154, "WINSHOW", "w",
                155, "MOVIEOPEN", "VwLS",
                156, "MOVIEPLAY", "L",
                157, "MOVIECLOSE", "L",
                158, "MOVIEMOVE", "LLL",
                159, "PICTURE", "VwLLLLLR",
                160, "LABEL", "VwLLLLSR",
                161, "SOUNDPLAY", "L",
                162, "CTLTEXT", "cSL",
                163, "SEROPEN", "LLLLL",
                164, "SERCLOSE", "L",
                165, "SERWRITE", "LS",
                166, "OPEN", "VLS",
                167, "CLOSE", "L",
                168, "WRITE", "LS",
                169, "SEEK", "LL",
                170, "CREATE", "SLL",
                171, "SPRITEFRAME", "Vw",
                172, "SPRITEDRAW", "LLLL",
                173, "SPRITECOPY", "LLLL",
                174, "SPRITEDRAWSIZE", "LLLLLL",
                175, "SPRITECOPYSIZE", "LLLLLL",
                176, "SPRITEBEGIN", "L",
                177, "SPRITEDONE", "Z",
                178, "SPRITEEND", "Z",
                179, "SPRITERELEASE", "L",
                180, "SPRITECLEAR", "L",
                181, "SPRITEDISPLAY", "L",
                182, "SPRITELOAD", "VL",
                183, "LISTBOX", "VwLLLLLR",
                184, "LISTADD", "cS",
                185, "DROPLIST", "VwLLLR",
                186, "ICON", "VwLLLLLR",
                187, "SPRITEUNLOAD", "L",
                188, "MICO33N", "VLLLLR",
                189, "SETCURSOR", "L",
                190, "SHOWCURSOR", "Z",
                191, "HIDECURSOR", "Z",
                192, "CLEARERROR", "Z",
                193, "ONERROR", "R",
                194, "BOXFILL", "wLLLL",
                195, "CIRCLEFILL", "wLLL",
                196, "ELLIPSEFILL", "wLLLL",
                197, "LINETO", "wLL",
                198, "DRAWTEXT", "wLLS",
                199, "DRAWFONT", "wL",
                200, "DRAWSIZE", "wL",
                201, "DRAWSTYLE", "wL",
                202, "SETCOLOR", "wL",
                203, "BACKCOLOR", "wL",
                204, "SETCOLORRGB", "wLLL",
                205, "BACKCOLORRGB", "wLLL",
                206, "WINREDRAW", "w",
                207, "EVENTS", "L",
                208, "PENSIZE", "wLL",
                209, "PENPATTERN", "wL",
                210, "PENMODE", "wL",
                211, "PENNORMAL", "w",
                212, "LISTCLEAR", "c",
                213, "LISTREMOVE", "cL",
                214, "TEXTBOXRO", "LL",
                215, "PRINTOPEN", "Z",
                216, "PRINTCLOSE", "Z",
                217, "NEWPAGE", "Z",
                218, "POKE", "LL",
                219, "POKEINT", "LL",
                220, "POKELONG", "LL",
                221, "MEMALLOC", "VL",
                222, "MEMFREE", "L",
                223, "MEMRESIZE", "LL",
                224, "MEMFILL", "LLLL",
                225, "MEMINT", "LLL",
                226, "MEMLONG", "LLL",
                227, "MEMSINGLE", "LLL",
                228, "MEMDOUBLE", "LLL",
                229, "MEMSTRING", "LLS",
                230, "TEXTSELECT", "cLL",
                231, "LISTSELECT", "cL",
                232, "LISTDESELECT", "cL",
                233, "CTLVALUE", "cL",
                234, "CUT", "Z",
                235, "COPY", "Z",
                236, "PASTE", "Z",
                237, "CLEAR", "Z",
                238, "MENUBLANK", "Z",
                239, "MENUCLEAR", "Z",
                240, "MENUDELETE", "L",
                241, "MENUDELETEITEM", "LL",
                242, "MENUDISABLE", "LL",
                243, "MENUENABLE", "LL",
                244, "MENUINSERTITEM", "LLSSR",
                245, "MENUMARK", "LLL",
                246, "MENUREDRAW", "Z",
                247, "MENUTEXT", "LLS",
                248, "SUBMENU", "VLLR",
                249, "MENUPREPARE", "R",
                250, "CTLHILITE", "c",
                251, "STRETCHLINE", "wLLVV",
                252, "STRETCHBOX", "wLLVV",
                253, "STRETCHELLIPSE", "wLLVV",
                254, "STRETCHCIRCLE", "wLLV",
                255, "SOUNDLOAD", "VL",
                256, "SOUNDUNLOAD", "L",
                257, "DELAY", "L",
                258, "CTLALIGN", "cL",
                259, "WINCLIP", "wLLLL",
                260, "SERSET", "LLLLL",
                261, "CONSOLE", "L",
                262, "PICTUREBEGIN", "wL",
                263, "PICTUREDONE", "Z",
                264, "PICTURESAVE", "S",
                265, "CLEARGRAPHICS", "w",
                266, "CLEARCONTROLS", "w",
                267, "CLEARWINDOW", "w",
                268, "DELETE", "S",
                269, "DRAWUPDATE", "wL",
                270, "SETCMDKEY", "LR",
                271, "WRITEBUFFER", "LLLL",
                272, "SCROLLSET", "cLLL",
                273, "ALERTBOX", "L",
                274, "COPYFILE", "SS",
                275, "RENAME", "SS",
                276, "LOCK", "S",
                277, "UNLOCK", "S",
                278, "LOADPALETTE", "LLLL",
                279, "WINPALETTE", "wL",
                280, "SETDEPTH", "L",
                281, "WINORIGIN", "wLL",
                282, "DRAWPICTURE", "wLLLLL",
                283, "INPUT", "m",
                284, "FORM", "w",
                285, "TIMER", "VwLLR",
                286, "CONMSG", "L",
                287, "SPRITEDUP", "LL",
                9999, "*", "Q",
        };
struct fun_list {
    short num;
    char name[16];
    char params[10];
    char ret;        //#11 is return (actually10)
} func_list[500] =
        {
                100, "ABS", "L", 'L',
                101, "VAL", "S", 'L',
                102, "CHR", "L", 'S',
                103, "ATAN", "L", 'L',
                104, "ACOS", "L", 'L',
                105, "ASIN", "L", 'L',
                106, "COS", "L", 'L',
                107, "LOG", "L", 'L',
                108, "SIN", "L", 'L',
                109, "SQR", "L", 'L',
                110, "TAN", "L", 'L',
                111, "LEN", "S", 'L',
                112, "DATE", "", 'S',
                113, "LCASE", "S", 'S',
                114, "UCASE", "S", 'S',
                115, "TRIM", "S", 'S',
                116, "LTRIM", "S", 'S',
                117, "RTRIM", "S", 'S',
                118, "SPACE", "L", 'S',
                119, "STR", "Ll", 'S',
                120, "STRING", "LL", 'S',
                121, "RND", "LL", 'L',
                122, "CTLTEXT", "c", 'S',
                123, "SERREAD", "LL", 'S',
                124, "SERAVAIL", "L", 'L',
                125, "READ", "LL", 'S',
                126, "FILEEXIST", "S", 'L',
                127, "LOF", "L", 'L',
                128, "LOC", "L", 'L',
                129, "EOF", "L", 'L',
                130, "SPRITEWIDTH", "L", 'L',
                131, "SPRITEHEIGHT", "L", 'L',
                132, "SERAVAIL", "L", 'L',
                133, "TIME", "", 'S',
                134, "DAY", "S", 'S',
                135, "WINBORDER", "wL", 'L',
                136, "SCREENBORDER", "L", 'L',
                137, "TIMER", "", 'L',
                138, "LISTCOUNT", "c", 'L',
                139, "ERRORNUM", "", 'L',
                140, "ERRORMSG", "", 'S',
                141, "PAGESETUP", "", 'L',
                142, "PRINTSETUP", "", 'L',
                143, "LAUNCH", "S", 'L',
                144, "PEEK", "L", 'L',
                145, "PEEKINT", "L", 'L',
                146, "PEEKLONG", "L", 'L',
                147, "VARADDR", "V", 'L',
                148, "MEMINT", "LL", 'L',
                149, "MEMLONG", "LL", 'L',
                150, "MEMSINGLE", "LL", 'L',
                151, "MEMDOUBLE", "LL", 'L',
                152, "MEMSTRING", "LLL", 'S',
                153, "MEMSIZE", "L", 'L',
                154, "TEXTLEN", "c", 'L',
                155, "TEXTSTART", "c", 'L',
                156, "TEXTEND", "c", 'L',
                157, "TEXTSELECT", "c", 'S',
                158, "LISTNUMSEL", "c", 'L',
                159, "LISTSELECT", "cL", 'L',
                160, "LISTITEM", "cL", 'S',
                161, "CTLVALUE", "c", 'L',
                162, "EVENTMOUSEX", "", 'L',
                163, "EVENTMOUSEY", "", 'L',
                164, "MOUSEX", "", 'L',
                165, "MOUSEY", "", 'L',
                166, "MOUSEDOWN", "", 'L',
                167, "KEYSDOWN", "", 'L',
                168, "IFKEY", "L", 'L',
                169, "GETKEYS", "", 'S',
                170, "FONTNUM", "S", 'L',
                171, "MENUCOUNT", "L", 'L',
                172, "MENUMARK", "LL", 'L',
                173, "MENUTEXT", "LL", 'S',
                174, "MSGBOX", "SL", 'L',
                175, "EVENTCODE", "L", 'L',
                176, "SOUNDPLAYING", "L", 'L',
                177, "ISMOVIE", "", 'L',
                178, "ISSOUND", "", 'L',
                179, "ISSPEECH", "", 'L',
                180, "SPEECHBUSY", "", 'L',
                181, "CTLBORDER", "cL", 'L',
                182, "OPENDIALOG", "S", 'S',
                183, "SAVEDIALOG", "SS", 'S',
                184, "CLIPAVAIL", "", 'L',
                185, "STRRES", "L", 'S',
                186, "STRRESLEN", "L", 'L',
                187, "FILENAME", "S", 'S',
                188, "POWERPC", "", 'L',
                189, "MID", "SLL", 'S',
                190, "LEFT", "SL", 'S',
                191, "RIGHT", "SL", 'S',
                192, "SPRITEHIT", "LLL", 'L',
                193, "PICTURELOAD", "S", 'L',
                194, "AND", "LL", 'L',
                195, "OR", "LL", 'L',
                196, "XOR", "LL", 'L',
                197, "EXP", "L", 'L',
                198, "POWER", "LL", 'L',
                199, "FILESIZE", "S", 'L',
                200, "TYPECVT", "S", 'L',
                201, "MOD", "LL", 'L',
                202, "ASC", "S", 'L',
                203, "READBUFFER", "LLLL", 'L',
                204, "PI", "", 'L',
                205, "DEGTORAD", "L", 'L',
                206, "RADTODEG", "L", 'L',
                207, "GETDEPTH", "", 'L',
                208, "HASDEPTH", "L", 'L',
                209, "LINEINPUT", "L", 'S',
                210, "CALL", "LLLLL", 'L',
                211, "WINHANDLE", "w", 'L',
                212, "CTLHANDLE", "c", 'L',
                213, "MEMHANDLE", "L", 'L',
                214, "WINEXIST", "w", 'L',
                215, "CTLEXIST", "c", 'L',
                216, "NOT", "L", 'L',
                217, "WINNUM", "w", 'L',
                218, "CTLNUM", "c", 'L',
                219, "FRONTWINDOW", "", 'S',
                220, "WINTITLE", "w", 'S',
                221, "GETPIXEL", "wLL", 'L',
                222, "RGB", "LLL", 'L',
                223, "APPLPATH", "", 'S',
                0, "***", "", 0
        };
